### ISSUE TITLE
[@vue/test-utils] i18n property translations of SFC not being used in unit test

### ISSUE THREAD

**Issue by brennj** [kazupon/vue-i18n-jest#1]
### Reproduction Link
https://codesandbox.io/s/2z362mk09r?module=%2Fsrc%2FApp.test.js

### Steps to reproduce
You'll see in `App.vue` that `$t('greeting')` is being used to display a message to the user, where `greeting` is defined in `i18n` of the SFC.

### What is Expected?
It works as expected on the browser, this should also happen on the test.

```js
<template>
  <div>{{ $t("greeting") }}</div>
</template>

<script>
export default {
  i18n: {
    messages: {
      en: {
        greeting: "Hello World!"
      }
    }
  }
};
</script>
```

### What is actually happening?
With Jest and `@vue/test-utils`, it will only show the translation key.

```js
expect(received).toEqual(expected)

Expected value to equal:
  "Hello World!"
Received:
  "greeting"

   9 | it("Should translate", () => {
  10 |   const wrapper = mount(App, { i18n, localVue });
> 11 |   expect(wrapper.text()).toEqual("Hello World!");
  12 | });
```

Not sure whether this is for @eddyerburgh or you guys, whatever suits! Hope it makes sense.

**Comment by kazupon** [comment]
releese out vue-jest@0.1.1
