### ISSUE TITLE
Accept new versions of vue-jest for vue 2

### ISSUE THREAD

**Issue by afontcu** [kazupon/vue-i18n-jest#38]
Hi! `vue-jest` 4.0.1 has been released, and the current peerDep definition of `-beta.3` does not include this patch version.

Also, `@vue/vue2-jest` has been [released](https://github.com/vuejs/vue-jest/releases), and I think the following versions should be supported, too: `^27.0.0 || ^27.0.0-alpha`.

I was about to open a PR but I'm not sure how to define all the 4 versions – if needed?

👋

**Comment by kazupon** [comment]
I've just released v1.1.1
Please check it!

> Thank you for your feedback! :)
> 
> You’ve said, I also think that vue-i18n-jest should be supported for Vue 2 / Vue 3 and jest 26 / jest 27 like vue-jest.
> 
> Currently, vue-i18n-jest does not have a package/repo structure that takes for them. Maybe it should be a monorepo like vue-jest. :)

I've opened it as a new issue.
In About this, If it needs, we can discuss the below issue. 
https://github.com/intlify/vue-i18n-jest/issues/42

Thanks!
