### ISSUE TITLE
Does it support Vue3?

### ISSUE THREAD

**Issue by nagisaando** [kazupon/vue-i18n-jest#53]
Hi, I'm not sure if this place is the appropriate place to ask but I think it says there is version 2 for Vue 3, and is it available? I can not install vue-i18-jest since it can not resolve dependency of vue 

```
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.5" from vue-i18n-jest@1.1.1
```

I am using 
```
"vue": "^3.2.31",
"vue-i18n": "^9.1.10",
"vite": "^2.5.4",
"vitest": "^0.15.2",
```

**Comment by nagisaando** [comment]
Vite does not use loader so obviously I do not need to do as when I was using webpack. Sorry about that!

**Comment by ivolkoff** [comment]
@nagisaando Please tell me how you solved the problem? I didn't understand

**Comment by nagisaando** [comment]
@ivolkoff 

Im using vite and vue3 with vue-i18n. 
I installed https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n and just followed the instruction and it should work

Vue CLI needs to compile the code with webpack that's why we needed this but vite does not need to complile code so we dont even need this
